# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-27 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uygulama',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='uygulama',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='uygulama',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Başlık'),
        ),
    ]
