# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-28 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0002_auto_20191127_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uygulama',
            name='content',
        ),
        migrations.RemoveField(
            model_name='uygulama',
            name='publishing_date',
        ),
        migrations.AlterField(
            model_name='uygulama',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Kullanıcı İsmi'),
        ),
    ]
