# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0003_auto_20191128_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uygulama',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Başlık'),
        ),
    ]
